# config/meta.yml

meta_product_name: "Helloradius"
meta_title: "Helloradius.co - Your Instagram Experts"
meta_description: "Helloradius is a social media agency focus on Instagram.
  Our goal is to increase significantly your traffic and your engagement. Saving
  you time is also one of our biggest concern, we want you to just focus on taking
  care of your community while we’re doing the rest!
  We are here to coach you through your journey on Instagram."

meta_image: "hellradius-banner-fb.png"            # Une image dans votre dossier app/assets/images/
twitter_account: "@helloradius.co"                # indispensable pour les Twitter Cards
